name: Deploy to GitHub Page

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupérer le code
        uses: actions/checkout@v4
        
      - name: ⚙️ Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: 📦 Installer les dépendances
        run: npm install
        
      - name: 🏗️ Compiler le site (Build)
        run: npm run build
        
      - name: 🔧 Préparer GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: 📤 Envoyer le dossier dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: 🚀 Déployer le site !
        id: deployment
        uses: actions/deploy-pages@v4
